### ISSUE TITLE
Installation ends with error

### ISSUE THREAD

**Issue by ChristopherJOlson** [Chia-Network/CAT-admin-tool#10]
Collecting chiavdf==1.0.3
  Using cached chiavdf-1.0.3.tar.gz (635 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'build_requires'
        warnings.warn(msg)
      running egg_info
      writing chiavdf.egg-info\PKG-INFO
      writing dependency_links to chiavdf.egg-info\dependency_links.txt
      writing top-level names to chiavdf.egg-info\top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'chiavdf.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in _get_build_requires
          self.run_setup()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 247, in <module>
          setup(
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 295, in run
          self.find_sources()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 302, in find_sources
          mm.run()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 537, in run
          self.add_defaults()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 581, in add_defaults
          self.read_manifest()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
          self.filelist.append(line)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 479, in append
          path = convert_path(item)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-4xw3v8zx\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 130, in convert_path
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path './' cannot end with '/'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Quexington** [comment]
Can you paste the command you ran as well as your python and pip versions?

**Comment by ChristopherJOlson** [comment]
Pip - 22.0.3
python - 3.10.2

Full Command

PS C:\Users\famsquad> python --version
Python 3.10.2
PS C:\Users\famsquad> cd .\CAT-admin-tool\
PS C:\Users\famsquad\CAT-admin-tool> .\venv\Scripts\activate
(venv) PS C:\Users\famsquad\CAT-admin-tool> pip install .
Processing c:\users\famsquad\cat-admin-tool
  Preparing metadata (setup.py) ... done
Collecting chia-blockchain@ git+https://github.com/Chia-Network/chia-blockchain.git@protocol_and_cats_rebased#23d571d9bb6b5003b49dee7ee31c1799358c5349
  Cloning https://github.com/Chia-Network/chia-blockchain.git (to revision protocol_and_cats_rebased) to c:\users\famsquad\appdata\local\temp\pip-install-q12vp1or\chia-blockchain_3a2dcd143c22449cba811c256ff365d8
  Running command git clone --filter=blob:none --quiet https://github.com/Chia-Network/chia-blockchain.git 'C:\Users\famsquad\AppData\Local\Temp\pip-install-q12vp1or\chia-blockchain_3a2dcd143c22449cba811c256ff365d8'
  Running command git checkout -b protocol_and_cats_rebased --track origin/protocol_and_cats_rebased
  Branch 'protocol_and_cats_rebased' set up to track remote branch 'protocol_and_cats_rebased' from 'origin'.
  Switched to a new branch 'protocol_and_cats_rebased'
  Resolved https://github.com/Chia-Network/chia-blockchain.git to commit 44cfeb0fb3bba1e951d6f73dcf5ddeac55f2d3d1
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting colorlog==5.0.1
  Using cached colorlog-5.0.1-py2.py3-none-any.whl (10 kB)
Collecting fasteners==0.16.3
  Using cached fasteners-0.16.3-py2.py3-none-any.whl (28 kB)
Collecting packaging==21.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting websockets==8.1.0
  Using cached websockets-8.1.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Collecting keyrings.cryptfile==1.3.4
  Using cached keyrings.cryptfile-1.3.4.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting chiavdf==1.0.3
  Using cached chiavdf-1.0.3.tar.gz (635 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'build_requires'
        warnings.warn(msg)
      running egg_info
      writing chiavdf.egg-info\PKG-INFO
      writing dependency_links to chiavdf.egg-info\dependency_links.txt
      writing top-level names to chiavdf.egg-info\top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'chiavdf.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\famsquad\CAT-admin-tool\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 247, in <module>
          setup(
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
          mm.run()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run
          self.add_defaults()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 584, in add_defaults
          self.read_manifest()
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
          self.filelist.append(line)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 482, in append
          path = convert_path(item)
        File "C:\Users\famsquad\AppData\Local\Temp\pip-build-env-zkx6taam\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 130, in convert_path
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path './' cannot end with '/'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) PS C:\Users\famsquad\CAT-admin-tool>

**Comment by Quexington** [comment]
Try pulling the latest commit, maybe an indirect dependency broke with that older version.

**Comment by ChristopherJOlson** [comment]
That worked Thanks!
