### ISSUE TITLE
run "cdv --help" error.

### ISSUE THREAD

**Issue by anchoret2009** [Chia-Network/CAT-admin-tool#11]
(venv) bogon:CAT-admin-tool mac$ cdv --help
Traceback (most recent call last):
  File "/Users/mac/Documents/pro_chia/chia_cat/CAT-admin-tool/venv/bin/cdv", line 5, in <module>
    from cdv.cmds.cli import main
  File "/Users/mac/Documents/pro_chia/chia_cat/CAT-admin-tool/venv/lib/python3.9/site-packages/cdv/cmds/cli.py", line 14, in <module>
    from cdv.cmds import (
  File "/Users/mac/Documents/pro_chia/chia_cat/CAT-admin-tool/venv/lib/python3.9/site-packages/cdv/cmds/chia_inspect.py", line 17, in <module>
    from chia.consensus.cost_calculator import calculate_cost_of_program, NPCResult
ImportError: cannot import name 'calculate_cost_of_program' from 'chia.consensus.cost_calculator' (/Users/mac/Documents/pro_chia/chia_cat/CAT-admin-tool/venv/lib/python3.9/site-packages/chia/consensus/cost_calculator.py)

I try these on Mac and Linux, both got same error.

**Comment by Jsewill** [comment]
I can confirm this behavior.

**Comment by Quexington** [comment]
This should be fixed with the latest version of cdv
